### ISSUE TITLE
ACTIVIDAD 1 INFOGRAFÍA DIEGO CRUZ CRUZ 

### ISSUE THREAD

**Issue by Diegocruz040708** [SistemasTecTlaxiaco/actividad-1-infografia-Diegocruz040708#1]
![ciclo de vida del desarrollo de un sistema (SDLC)](https://github.com/user-attachments/assets/e3daa5a4-ca32-4dd1-bc1f-568fc5113198)

**Comment by Anakimberly** [comment]
Tienes el 20% cumple con los criterios que se mencionan en la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
